// SCAR · Skin CARe
// Todo el contenido personal se guarda localmente en IndexedDB.
const DB_NOMBRE='scar-db', DB_VERSION=1;
let db, fechaActual=fechaISO(new Date()), mesVisible=new Date();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

function fechaISO(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),dia=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${dia}`}
function escapar(t=''){return String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('visible');setTimeout(()=>e.classList.remove('visible'),1800)}

function abrirDB(){return new Promise((ok,no)=>{const r=indexedDB.open(DB_NOMBRE,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;d.createObjectStore('productos',{keyPath:'id'});d.createObjectStore('rutinas',{keyPath:'id'});d.createObjectStore('registros',{keyPath:'fecha'});d.createObjectStore('ciclos',{keyPath:'id'});d.createObjectStore('sintomas',{keyPath:'id'});d.createObjectStore('ajustes',{keyPath:'clave'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function store(nombre,modo='readonly'){return db.transaction(nombre,modo).objectStore(nombre)}
function todos(nombre){return new Promise((ok,no)=>{const r=store(nombre).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function obtener(nombre,id){return new Promise((ok,no)=>{const r=store(nombre).get(id);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function guardar(nombre,obj){return new Promise((ok,no)=>{const r=store(nombre,'readwrite').put(obj);r.onsuccess=()=>ok(obj);r.onerror=()=>no(r.error)})}
function borrar(nombre,id){return new Promise((ok,no)=>{const r=store(nombre,'readwrite').delete(id);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}

async function precargar(){if((await todos('productos')).length===0){for(const p of [
{id:'limpiador',nombre:'Jabón / limpiador facial',categoria:'Limpieza',momento:'ambos',activo:true,eliminado:false,notas:''},
{id:'micelar',nombre:'Agua micelar',categoria:'Limpieza',momento:'noche',activo:true,eliminado:false,notas:''},
{id:'hidratante',nombre:'Crema hidratante',categoria:'Hidratación',momento:'ambos',activo:true,eliminado:false,notas:''},
{id:'vitamina-c',nombre:'Sérum de vitamina C',categoria:'Sérum',momento:'mañana',activo:true,eliminado:false,notas:''}
])await guardar('productos',p)}
if((await todos('sintomas')).length===0){for(const n of ['Cólicos','Hinchazón','Sensibilidad en la piel','Piel grasa','Piel seca','Granitos','Dolor de cabeza','Cansancio'])await guardar('sintomas',{id:crypto.randomUUID(),nombre:n,activo:true})}}

async function registro(fecha=fechaActual){return (await obtener('registros',fecha))||{fecha,productosUsados:{mañana:[],noche:[]},rutinas:{mañana:null,noche:null},notas:'',fotos:[],sintomas:[]}}
async function renderHoy(){const [productos,rutinas,sintomas,r]=await Promise.all([todos('productos'),todos('rutinas'),todos('sintomas'),registro()]);
for(const momento of ['mañana','noche']){const cont=$(`#productos${momento==='mañana'?'Manana':'Noche'}`);const lista=productos.filter(p=>p.activo&&!p.eliminado&&(p.momento===momento||p.momento==='ambos'));cont.innerHTML=lista.map(p=>`<label class="check ${r.productosUsados?.[momento]?.includes(p.id)?'usado':''}"><input type="checkbox" data-prod="${p.id}" data-momento="${momento}" ${r.productosUsados?.[momento]?.includes(p.id)?'checked':''}><span>${escapar(p.nombre)}</span></label>`).join('')||'<p class="ayuda">No hay productos activos para este momento.</p>';
const sel=$(momento==='mañana'?'#rutinaManana':'#rutinaNoche');sel.innerHTML='<option value="">Sin rutina · registro libre</option>'+rutinas.filter(x=>x.activa!==false&&(x.momento===momento||x.momento==='cualquiera')).map(x=>`<option value="${x.id}">${escapar(x.nombre)}</option>`).join('');sel.value=r.rutinas?.[momento]||''}
$('#notasHoy').value=r.notas||'';$('#sintomasHoy').innerHTML=sintomas.filter(s=>s.activo).map(s=>`<button class="chip ${r.sintomas?.includes(s.id)?'activo':''}" data-sintoma="${s.id}">${escapar(s.nombre)}</button>`).join('');renderFotos(r);await renderCiclo()}
function renderFotos(r){$('#contadorFotos').textContent=`${r.fotos?.length||0}/3`;$('#fotosHoy').innerHTML='';(r.fotos||[]).forEach((b,i)=>{const u=URL.createObjectURL(b),d=document.createElement('div');d.className='foto';d.innerHTML=`<img alt="Foto de piel ${i+1}" src="${u}"><button data-borrar-foto="${i}" aria-label="Borrar foto">×</button>`;$('#fotosHoy').append(d)})}

async function cambiarProducto(e){const c=e.target.closest('[data-prod]');if(!c)return;const r=await registro(),m=c.dataset.momento,id=c.dataset.prod;r.productosUsados[m]=r.productosUsados[m]||[];r.productosUsados[m]=c.checked?[...new Set([...r.productosUsados[m],id])]:r.productosUsados[m].filter(x=>x!==id);await guardar('registros',r);renderHoy()}
async function guardarNotas(){const r=await registro();r.notas=$('#notasHoy').value;await guardar('registros',r)}
async function toggleSintoma(id){const r=await registro();r.sintomas=r.sintomas||[];r.sintomas=r.sintomas.includes(id)?r.sintomas.filter(x=>x!==id):[...r.sintomas,id];await guardar('registros',r);renderHoy()}
async function elegirRutina(m,id){const r=await registro();r.rutinas=r.rutinas||{};r.rutinas[m]=id||null;if(id){const ru=await obtener('rutinas',id);if(ru)r.productosUsados[m]=[...new Set([...(r.productosUsados[m]||[]),...ru.productos])]}await guardar('registros',r);renderHoy()}

async function comprimir(file){const bmp=await createImageBitmap(file),max=1200,esc=Math.min(1,max/Math.max(bmp.width,bmp.height)),c=document.createElement('canvas');c.width=Math.round(bmp.width*esc);c.height=Math.round(bmp.height*esc);c.getContext('2d').drawImage(bmp,0,0,c.width,c.height);return new Promise(ok=>c.toBlob(ok,'image/jpeg',.8))}
async function agregarFoto(file){if(!file)return;const r=await registro();if((r.fotos||[]).length>=3)return toast('Máximo 3 fotos por día');const blob=await comprimir(file);r.fotos=[...(r.fotos||[]),blob];await guardar('registros',r);renderHoy();toast('Foto guardada localmente')}
async function borrarFoto(i){const r=await registro();r.fotos.splice(i,1);await guardar('registros',r);renderHoy()}

async function renderProductos(){const ps=await todos('productos'),rs=await todos('rutinas');$('#listaProductos').innerHTML=ps.filter(p=>!p.eliminado).map(p=>`<div class="item"><div class="item-top"><div><strong>${escapar(p.nombre)}</strong><p>${escapar(p.categoria)} · ${p.momento} · ${p.activo?'Activo':'Inactivo'}</p></div><div class="acciones"><button class="texto" data-editar-producto="${p.id}">Editar</button></div></div></div>`).join('');$('#listaRutinas').innerHTML=rs.map(r=>`<div class="item"><div class="item-top"><div><strong>${escapar(r.nombre)}</strong><p>${r.momento} · ${r.productos.length} productos</p></div><button class="texto" data-editar-rutina="${r.id}">Editar</button></div></div>`).join('')||'<p class="ayuda">Todavía no creaste rutinas. Podés registrar productos libremente.</p>'}
function modal(html){$('#modalContenido').innerHTML=html;$('#modal').showModal()}
async function modalProducto(id){const p=id?await obtener('productos',id):{id:crypto.randomUUID(),nombre:'',categoria:'',momento:'ambos',activo:true,notas:''};modal(`<h2>${id?'Editar':'Nuevo'} producto</h2><input type="hidden" name="tipo" value="producto"><input type="hidden" name="id" value="${p.id}"><label class="campo-label">Nombre</label><input name="nombre" required value="${escapar(p.nombre)}"><label class="campo-label">Categoría</label><input name="categoria" value="${escapar(p.categoria)}"><label class="campo-label">Momento</label><select name="momento"><option ${p.momento==='mañana'?'selected':''}>mañana</option><option ${p.momento==='noche'?'selected':''}>noche</option><option ${p.momento==='ambos'?'selected':''}>ambos</option></select><label class="check"><input type="checkbox" name="activo" ${p.activo?'checked':''}> Activo</label><br><button class="boton" value="guardar">Guardar</button>${id?'<button class="texto" name="eliminar" value="1">Eliminar del uso actual</button>':''}`)}
async function modalRutina(momento='cualquiera',id){const ps=(await todos('productos')).filter(p=>!p.eliminado),r=id?await obtener('rutinas',id):{id:crypto.randomUUID(),nombre:'',momento,productos:[],activa:true};modal(`<h2>${id?'Editar':'Crear'} rutina</h2><input type="hidden" name="tipo" value="rutina"><input type="hidden" name="id" value="${r.id}"><label class="campo-label">Nombre</label><input name="nombre" required value="${escapar(r.nombre)}" placeholder="Ej. Mañana rápida"><label class="campo-label">Momento</label><select name="momento"><option ${r.momento==='mañana'?'selected':''}>mañana</option><option ${r.momento==='noche'?'selected':''}>noche</option><option value="cualquiera" ${r.momento==='cualquiera'?'selected':''}>cualquiera</option></select><label class="campo-label">Productos</label>${ps.map(p=>`<label class="check"><input type="checkbox" name="productos" value="${p.id}" ${r.productos.includes(p.id)?'checked':''}>${escapar(p.nombre)}</label>`).join('')}<br><button class="boton" value="guardar">Guardar rutina</button>`) }

async function guardarModal(e){e.preventDefault();const f=new FormData(e.target),tipo=f.get('tipo');if(tipo==='producto'){const viejo=await obtener('productos',f.get('id'));await guardar('productos',{...(viejo||{}),id:f.get('id'),nombre:f.get('nombre'),categoria:f.get('categoria'),momento:f.get('momento'),activo:f.get('activo')==='on',eliminado:f.get('eliminar')==='1',notas:viejo?.notas||''})}else if(tipo==='rutina'){await guardar('rutinas',{id:f.get('id'),nombre:f.get('nombre'),momento:f.get('momento'),productos:f.getAll('productos'),activa:true})}$('#modal').close();await renderProductos();await renderHoy();toast('Guardado')}

async function renderCiclo(){const cs=(await todos('ciclos')).sort((a,b)=>a.fechaInicio.localeCompare(b.fechaInicio)),abierto=cs.find(c=>!c.fechaFin);$('#botonPeriodo').textContent=abierto?'Terminó mi período':'Empezó mi período';if(cs.length<2){$('#faseHoy').textContent=abierto?'Fase menstrual · registrada':'Todavía no tengo datos suficientes';return}const completos=cs.filter(c=>c.fechaFin);const ult=cs.slice(-6);const largos=[];for(let i=1;i<ult.length;i++)largos.push((new Date(ult[i].fechaInicio+'T12:00')-new Date(ult[i-1].fechaInicio+'T12:00'))/86400000);const prom=largos.length?Math.round(largos.reduce((a,b)=>a+b,0)/largos.length):28;const inicio=new Date(cs.at(-1).fechaInicio+'T12:00'),hoy=new Date(fechaActual+'T12:00'),dia=Math.floor((hoy-inicio)/86400000)+1;let fase='folicular';if(abierto||dia<=5)fase='menstrual';else if(dia>=prom-15&&dia<=prom-13)fase='ovulación';else if(dia>prom-13)fase='lútea';$('#faseHoy').textContent=`Fase estimada: ${fase}`;const prox=new Date(inicio);prox.setDate(prox.getDate()+prom);const faltan=Math.ceil((prox-hoy)/86400000);$('#prediccionCiclo').textContent=`Próximo período estimado: ${faltan>=0?`en ~${faltan} días`:'fecha estimada superada'}. Predicción orientativa basada en tus registros.`}
async function togglePeriodo(){const cs=await todos('ciclos'),ab=cs.find(c=>!c.fechaFin);if(ab){ab.fechaFin=fechaActual;await guardar('ciclos',ab)}else await guardar('ciclos',{id:crypto.randomUUID(),fechaInicio:fechaActual,fechaFin:null,notas:''});renderHoy();toast('Ciclo actualizado')}
function modalCiclo(){modal(`<h2>Cargar período pasado</h2><input type="hidden" name="tipo" value="ciclo"><label class="campo-label">Inicio</label><input type="date" name="inicio" required><label class="campo-label">Fin</label><input type="date" name="fin"><br><br><button class="boton" value="guardar">Guardar</button>`)}

async function renderCalendario(){const regs=await todos('registros'),cs=await todos('ciclos'),y=mesVisible.getFullYear(),m=mesVisible.getMonth(),prim=new Date(y,m,1),dias=new Date(y,m+1,0).getDate(),offset=(prim.getDay()+6)%7,nombres=['L','M','X','J','V','S','D'];let h=`<div class="cal-head"><button class="texto" data-mes="-1">‹</button><h2>${prim.toLocaleDateString('es',{month:'long',year:'numeric'})}</h2><button class="texto" data-mes="1">›</button></div><div class="cal-grid">${nombres.map(n=>`<div class="cal-semana">${n}</div>`).join('')}${'<div></div>'.repeat(offset)}`;for(let d=1;d<=dias;d++){const f=fechaISO(new Date(y,m,d)),reg=regs.find(r=>r.fecha===f),per=cs.some(c=>f>=c.fechaInicio&&f<=(c.fechaFin||fechaActual));h+=`<button class="cal-dia ${reg?'con-registro':''} ${per?'periodo-dia':''}" data-fecha="${f}">${d}</button>`}$('#calendario').innerHTML=h+'</div>'}

async function renderEvolucion(){const regs=await todos('registros'),ps=await todos('productos');const conDatos=regs.filter(r=>(r.productosUsados?.mañana?.length||0)+(r.productosUsados?.noche?.length||0)>0);let uso=ps.filter(p=>!p.eliminado).map(p=>{const n=conDatos.filter(r=>[...(r.productosUsados?.mañana||[]),...(r.productosUsados?.noche||[])].includes(p.id)).length;return `<div class="item"><strong>${escapar(p.nombre)}</strong><p>${conDatos.length?Math.round(n/conDatos.length*100):0}% de los días con datos</p></div>`}).join('');$('#evolucion').innerHTML=`<div class="tarjeta"><p class="eyebrow">REGISTROS</p><h2>${regs.length} días guardados</h2><p class="ayuda">Las estadísticas usan únicamente días con datos. No rellenamos días faltantes.</p></div><h2 class="separador">Uso de productos</h2>${uso}<h2 class="separador">Piel y ciclo</h2><p class="ayuda">Esta sección irá ganando valor cuando acumules registros de síntomas y varios ciclos. Las fases son estimaciones, no información médica.</p>`}

async function renderAjustes(){let est='No disponible';if(navigator.storage?.estimate){const e=await navigator.storage.estimate();est=`${((e.usage||0)/1048576).toFixed(1)} MB usados`;}$('#ajustes').innerHTML=`<div class="item"><strong>Almacenamiento local</strong><p>${est}</p><button class="texto" id="persistir">Pedir almacenamiento persistente</button></div><div class="item"><strong>Backup</strong><p>Exportá periódicamente tus datos. Las fotos se incluyen en base64.</p><button class="boton secundario" id="exportar">Exportar JSON</button></div><div class="item"><strong>Privacidad</strong><p>Los datos quedan en IndexedDB en este dispositivo. El futuro PIN de 4 dígitos será solo una traba visual: no cifrará la base de datos.</p></div>`}

async function exportar(){const datos={version:1,exportado:new Date().toISOString()};for(const n of ['productos','rutinas','registros','ciclos','sintomas','ajustes'])datos[n]=await todos(n);for(const r of datos.registros)r.fotos=await Promise.all((r.fotos||[]).map(blob=>new Promise(ok=>{const fr=new FileReader();fr.onload=()=>ok(fr.result);fr.readAsDataURL(blob)})));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(datos)],{type:'application/json'}));a.download=`scar-backup-${fechaActual}.json`;a.click();URL.revokeObjectURL(a.href)}

function navegar(v){$$('.vista').forEach(x=>x.classList.remove('activa'));$(`#vista-${v}`).classList.add('activa');$$('.barra button').forEach(x=>x.classList.toggle('activo',x.dataset.vista===v));if(v==='productos')renderProductos();if(v==='calendario')renderCalendario();if(v==='evolucion')renderEvolucion();if(v==='ajustes')renderAjustes();scrollTo(0,0)}

async function init(){db=await abrirDB();await precargar();$('#fechaHoy').textContent=new Date().toLocaleDateString('es',{weekday:'short',day:'numeric',month:'short'});await renderHoy();
$('.barra').addEventListener('click',e=>{const b=e.target.closest('[data-vista]');if(b)navegar(b.dataset.vista)});$('#productosManana').addEventListener('change',cambiarProducto);$('#productosNoche').addEventListener('change',cambiarProducto);$('#notasHoy').addEventListener('change',guardarNotas);$('#sintomasHoy').addEventListener('click',e=>{const b=e.target.closest('[data-sintoma]');if(b)toggleSintoma(b.dataset.sintoma)});$('#rutinaManana').addEventListener('change',e=>elegirRutina('mañana',e.target.value));$('#rutinaNoche').addEventListener('change',e=>elegirRutina('noche',e.target.value));$('#fotoInput').addEventListener('change',e=>agregarFoto(e.target.files[0]));$('#fotosHoy').addEventListener('click',e=>{const b=e.target.closest('[data-borrar-foto]');if(b)borrarFoto(+b.dataset.borrarFoto)});$('#botonPeriodo').onclick=togglePeriodo;$('#cargarPeriodoPasado').onclick=modalCiclo;
$('#nuevoProducto').onclick=()=>modalProducto();$('#nuevaRutina').onclick=()=>modalRutina();$$('[data-crear-rutina]').forEach(b=>b.onclick=()=>modalRutina(b.dataset.crearRutina));$('#listaProductos').onclick=e=>{const b=e.target.closest('[data-editar-producto]');if(b)modalProducto(b.dataset.editarProducto)};$('#listaRutinas').onclick=e=>{const b=e.target.closest('[data-editar-rutina]');if(b)modalRutina('cualquiera',b.dataset.editarRutina)};$('#formModal').addEventListener('submit',async e=>{const f=new FormData(e.target);if(f.get('tipo')==='ciclo'){e.preventDefault();await guardar('ciclos',{id:crypto.randomUUID(),fechaInicio:f.get('inicio'),fechaFin:f.get('fin')||null,notas:''});$('#modal').close();renderHoy();return}guardarModal(e)});$('#calendario').onclick=e=>{const b=e.target.closest('[data-mes]');if(b){mesVisible.setMonth(mesVisible.getMonth()+Number(b.dataset.mes));renderCalendario()}};$('#ajustes').onclick=async e=>{if(e.target.id==='exportar')exportar();if(e.target.id==='persistir'){const ok=await navigator.storage?.persist?.();toast(ok?'Almacenamiento persistente concedido':'El navegador no lo concedió')}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.error)}
init().catch(err=>{console.error(err);toast('No se pudo iniciar SCAR')});
