const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path');
const root = path.join(__dirname,'..');
(async()=>{
 const server = require('node:http').createServer((req,res)=>{const p=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);try{res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.png':'image/png','.json':'application/json'})[path.extname(p)]||'text/plain');res.end(fs.readFileSync(p));}catch{res.writeHead(404);res.end();}});
 await new Promise(r=>server.listen(4175,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.SCAR_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream'],headless:true});
 try {
 const context=await browser.newContext({viewport:{width:390,height:844},permissions:['camera','geolocation'],geolocation:{latitude:-25.28,longitude:-57.63}});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(() => { window.SCAR_TEST_GUEST = true; });
 await page.goto('http://127.0.0.1:4175');await page.locator('#freeCare').waitFor();
 assert.equal(await page.locator('#moreDetails').evaluate(e=>e.tagName),'SECTION');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow ${width}`);}
 await page.setViewportSize({width:390,height:844});
 await page.locator('#freeCare').click();await page.locator('#careForm [name=name]').fill('Mascarilla de tarde');await page.locator('#careForm [name=time]').fill('16:40');await page.locator('#careForm [name=product]').first().check();await page.locator('#careForm [name=notes]').fill('Solo mejilla izquierda');await page.locator('#careForm button[type=submit]').click();await page.locator('#extraDialog').waitFor({state:'hidden'});assert.match(await page.locator('#careList').textContent(),/16:40/);
 await page.locator('[data-care-edit]').click();await page.locator('#careForm [name=time]').fill('17:05');await page.locator('#careForm button[type=submit]').click();await page.locator('#extraDialog').waitFor({state:'hidden'});assert.match(await page.locator('#careList').textContent(),/17:05/);
 await page.locator('#registrarZona').click();await page.locator('#modal [name=zona_id]').selectOption('3');await page.locator('#modal [name=sintoma_id]').selectOption({label:'Granitos'});await page.locator('#modal [name=intensidad]').selectOption('3');await page.locator('#modal [name=notas]').fill('Dos cerca de la nariz');await page.locator('#modal button[type=submit]').click();await page.locator('#modal').waitFor({state:'hidden'});assert.match(await page.locator('#zonasHoy').textContent(),/Mejilla izquierda.*Granitos.*Fuerte.*Dos/s);
 // MIME can be empty in mobile file pickers.
 await page.locator('#fotoInput').setInputFiles({name:'phone-photo.jpg',mimeType:'',buffer:fs.readFileSync(path.join(root,'assets/icon-192.png'))});await page.locator('#modal button[type=submit]').click();await page.locator('#modal').waitFor({state:'hidden'});assert.equal(await page.locator('#fotosHoy img').count(),1);
 await page.locator('.barra [data-nav=calendario]').click();await page.locator('.cal-dia.today').click();await page.locator('#editSheet').waitFor();assert.match(await page.locator('#extraContent').textContent(),/Mascarilla de tarde.*17:05/s);assert.equal(await page.locator('.sheet-photos img').count(),1);await page.locator('#extraClose').click();
 await page.locator('.barra [data-nav=productos]').click();await page.locator('[data-edit-product]').first().click();await page.locator('#productPhoto').setInputFiles(path.join(root,'assets/icon-192.png'));await page.locator('#modal button[type=submit]').click();await page.locator('#modal').waitFor({state:'hidden'});await page.locator('.product-photo').waitFor();
 await page.locator('.barra [data-nav=comparar]').click();await page.locator('#compareImageA img').waitFor();await page.locator('#compareAngle').selectOption('perfil izquierdo');await page.waitForFunction(()=>document.querySelector('#compareImageA').textContent.includes('No hay foto'));
 await page.locator('.barra [data-nav=hoy]').click();
 await page.locator('#quickRoutine [data-new-routine]').click();await page.locator('#modal [name=nombre]').fill('Mi cuidado habitual');await page.locator('#modal [name=productos]').first().check();await page.locator('#modal button[type=submit]').click();await page.locator('#modal').waitFor({state:'hidden'});await page.locator('#didRoutine').click();await page.waitForFunction(()=>document.querySelectorAll('[data-care-edit]').length===2);
 const currentDate=await page.locator('#fechaActual').inputValue();const d=new Date(currentDate+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-1);const yesterday=d.toISOString().slice(0,10);await page.locator('#fechaActual').fill(yesterday);await page.locator('#fechaActual').dispatchEvent('change');await page.locator('#fotoInput').setInputFiles(path.join(root,'assets/icon-192.png'));await page.locator('#modal button[type=submit]').click();await page.locator('#modal').waitFor({state:'hidden'});await page.locator('#fechaActual').fill(currentDate);await page.locator('#fechaActual').dispatchEvent('change');await page.waitForFunction(()=>document.querySelectorAll('[data-care-edit]').length===2);
 await page.locator('.barra [data-nav=hoy]').click();await page.locator('#ghostCamera').click();assert.equal(await page.locator('#ghostOpacity').count(),0);await page.locator('#startCamera').click();await page.waitForFunction(()=>document.querySelector('#cameraVideo').videoWidth>0);await page.locator('#captureCamera').click();await page.locator('#extraDialog').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector('#contadorFotos').textContent==='2/3');
 await page.route('https://api.open-meteo.com/**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({current:{temperature_2m:24,relative_humidity_2m:70,time:'2026-09-16T12:00'}})}));await page.locator('#weatherCard summary').click();await page.locator('#weatherEnable').click();await page.waitForFunction(()=>document.querySelector('#weatherCard').textContent.includes('24 °C'));assert.match(await page.locator('#weatherCard').textContent(),/70 %/);
 await page.locator('.barra [data-nav=ajustes]').click();await page.waitForFunction(()=>document.querySelector('#evolucion').textContent.includes('Datos insuficientes'));assert.match(await page.locator('#evolucion').textContent(),/n = 1/);
 await page.locator('.barra [data-nav=hoy]').click();await page.screenshot({path:'/tmp/scar-v5-mobile.png',fullPage:true});await page.reload();await page.locator('[data-care-edit]').first().waitFor();assert.match(await page.locator('#careList').textContent(),/17:05/);assert.deepEqual(errors,[]);
 console.log('PASS V5 quick mode, arbitrary timed care, zone details, empty-MIME image, daily sheet, product photo, comparison missing angle, camera capture, weather API, sample guard and persistence');
 } finally {await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exit(1)});
